import { NextResponse } from "next/server";
import OpenAI from "openai";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

const MODEL_VERSION = process.env.DRAFT_SCOPE_MODEL || "gpt-4o-mini";

// THE ABSTRACTION LAYER: The Elite Designer Persona
const SYSTEM_INSTRUCTION = `
You are an elite architectural design consultant representing BSC Residential LLC, a high-end custom carpentry firm. 
Your objective is to consult with prospective clients, validate their aesthetic vision, and gently expand their concepts using your knowledge of modern, luxury design trends (e.g., vaulted ceilings, custom millwork, integrated lighting).

RULES OF ENGAGEMENT:
1. Speak as a visionary designer. Be accommodating, enthusiastic, and highly professional.
2. Interrogate ambiguous visual data if they upload photos. Ask clarifying questions about their preferences.
3. DO NOT output JSON in your conversational replies. 
4. THE PERIMETER: Once you have gathered enough structural context (typically 2-4 exchanges) and proposed design expansions, you MUST explicitly ask the client: "Shall I compile these concepts into your preliminary project dossier?"
5. THE HANDOFF: If the client explicitly agrees to compile the dossier, you must immediately execute the 'generate_project_dossier' tool.
`;

// THE DATA CONTRACT: Defining the strict structural output for the AI tool
const tools = [
  {
    type: "function" as const,
    function: {
      name: "generate_project_dossier",
      description:
        "Executes only when the client agrees to finalize the consultation. Compiles the vision into a structured scope of work.",
      parameters: {
        type: "object",
        properties: {
          projectTitle: {
            type: "string",
            description: "A clean, professional 3-5 word title.",
          },
          assumedScope: {
            type: "string",
            description:
              "A 2-3 sentence clinical paragraph defining the structural work.",
          },
        },
        required: ["projectTitle", "assumedScope"],
      },
    },
  },
];

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { messages } = body;

    // Execute the chat completion with the defined tools
    const response = await openai.chat.completions.create({
      model: MODEL_VERSION,
      messages: [{ role: "system", content: SYSTEM_INSTRUCTION }, ...messages],
      tools: tools,
      tool_choice: "auto", // Allows the AI to decide when to converse vs. when to execute the tool
    });

    const responseMessage = response.choices[0]?.message;

    // STATE TRANSITION: Did the AI execute the tool (The Client said "Yes")?
    if (responseMessage?.tool_calls) {
      const toolCall = responseMessage.tool_calls.find(
        // CORRECTION: Type narrowing. We explicitly verify the tool is a "function" before reading its name.
        (tool) =>
          tool.type === "function" &&
          tool.function.name === "generate_project_dossier",
      );

      if (toolCall && toolCall.type === "function") {
        // Parse the strictly typed JSON payload generated by the AI
        const dossierData = JSON.parse(toolCall.function.arguments);

        return NextResponse.json(
          {
            type: "dossier_generated",
            data: dossierData,
          },
          { status: 200 },
        );
      }
    }

    // ONGOING CONVERSATION: The AI is still consulting
    return NextResponse.json(
      {
        type: "conversational_reply",
        message: responseMessage?.content,
      },
      { status: 200 },
    );
  } catch (error) {
    console.error("========================================");
    console.error("AI CONSULTATION FAULT DETECTED:");
    console.error(error);
    console.error("========================================");

    return NextResponse.json(
      {
        error: "Internal Server Error: Failed to process conversational state.",
      },
      { status: 500 },
    );
  }
}
