// src/lib/types/database.ts

/**
 * 1. THE PROPERTY LEDGER
 * Geographic locations anchored to a specific client.
 */
export interface Property {
  id: string; // UUID generated by Supabase
  client_id: string; // UUID anchoring the property to the authenticated user
  street_address: string;
  zip_code: string;
  created_at: string; // ISO Timestamp
}

/**
 * 2. THE PROJECT LEDGER
 * The core project dossier, structurally bound to both the Client and a specific Property.
 */
export interface Project {
  id: string;
  client_id: string;
  property_id: string; // The critical linkage for historical sorting
  title: string;
  status:
    | "Intake Review"
    | "Consultation Requested"
    | "Active Build"
    | "Completed";
  project_type: string;
  scope_description: string;
  budget_range: string;
  timeline_expectation: string;
  created_at: string;
}

/**
 * 3. DIRECT COMMUNICATION (ASYNCHRONOUS CHAT)
 * Message payloads for the portal's communication feed.
 */
export interface Message {
  id: string;
  project_id: string; // Links message to a specific project ledger
  sender_id: string; // UUID of either the Client or the Operator
  text_payload: string;
  created_at: string;
}

/**
 * 4. SITE LOGS (THE OPERATOR'S FIELD UPDATES)
 * Timestamped progress updates pushed from the field.
 */
export interface SiteLog {
  id: string;
  project_id: string; // Links the log to a specific project
  operator_id: string; // Your secure UUID
  title: string;
  description: string;
  image_url?: string; // Optional: Supabase Storage URL for the compressed .webp image
  created_at: string;
}

// 1. The Junction Table Contract
export interface ProjectStakeholder {
  id: string;
  project_id: string; // Links to the specific build
  user_id: string; // The authenticated user (Client A, Client B, or Operator)
  role: "primary_client" | "secondary_client" | "operator";
  joined_at: string;
}
